CREATE DATABASE IF NOT EXISTS mi_disco_duro;
USE mi_disco_duro;
CREATE TABLE  usuarios(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nick VARCHAR(20) UNIQUE,
telefono VARCHAR(20) NOT NULL,
email VARCHAR(20) UNIQUE NOT NULL ,
contrasena VARCHAR(20) NOT NULL,
direccion VARCHAR(50) NOT NULL,
nombre VARCHAR(20) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
foto VARCHAR (50) NOT NULL
);
CREATE TABLE carpetas(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
fecha_de_modificacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
nombre VARCHAR(20) NOT NULL,
id_usuarios INT UNSIGNED ,
id_carpetas INT UNSIGNED ,
 FOREIGN KEY (id_carpetas) REFERENCES carpetas(id) ON DELETE CASCADE,
 FOREIGN KEY (id_usuarios) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE TABLE ficheros(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
fecha_de_modificacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
tipo VARCHAR(4),
nombre VARCHAR(20) NOT NULL,
id_carpetas INT UNSIGNED,
FOREIGN KEY (id_carpetas) REFERENCES carpetas(id)
);
