CREATE DATABASE IF NOT EXISTS proyecto;
USE proyecto;
CREATE TABLE  usuarios(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,


email VARCHAR(20) UNIQUE NOT NULL ,
password VARCHAR(128) NOT NULL,
nombre VARCHAR(20) NOT NULL,
foto VARCHAR (50) NOT NULL
);
CREATE TABLE carpetas(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
fecha_de_modificacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
nombre VARCHAR(100) NOT NULL,
ruta VARCHAR(120),
id_usuarios INT UNSIGNED ,
id_carpetas INT UNSIGNED ,
 FOREIGN KEY (id_carpetas) REFERENCES carpetas(id) ON DELETE CASCADE,
 FOREIGN KEY (id_usuarios) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE TABLE ficheros(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
fecha_de_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
nombre VARCHAR(100) NOT NULL,
ruta VARCHAR(120),
nombre_carpetasVARCHAR(100) NOT NULL, 
FOREIGN KEY (id_carpetas) REFERENCES carpetas(id) ON DELETE CASCADE
);
